### ISSUE TITLE
Problem to retrive some spectra index.

### ISSUE THREAD

**Issue by Maux82** [pymzml/pymzML#100]
Hi,

I got into some strange behaivour processing one of my raw file.
Actually in my application I extract Xic within a certain rt intenval and fix mz. 
First to extract the Xic, in order to speed the computation, I read all the spectras and I save  their ID and scan_time  something like:
`      run =    pymzml.run.Reader(name,MS1_Precision=5e-6)
       for spectrum in run:
            if spectrum.ms_level == 1:
                rt_list.append(spectrum.scan_time)
                runid_list.append(spectrum.ID)`

Later, if acces particular spectra index  I get  this error 
`xml.etree.ElementTree.ParseError: junk after document element: line 42, column 8`.
This is strange, because inside the for loop I able to see it but then I can't  access anymore.

Do yoy think is it somehow related with conversion from Thermo to mzMl ?  I can send you the mzML file if you needed.

Thank in advance 
Cheers
Andrea

**Comment by Maux82** [comment]
I re-initialize 'run'  but I still don't find certain spectra. 

my code is :  
```
run = pymzml.run.Reader(name,MS1_Precision=5e-6) 
for spectrum in run: 
    if spectrum.ms_level == 1:
        rt_list.append(spectrum.scan_time)
        runid_list.append(spectrum.ID)
```
[see the function in my code ](https://github.com/compomics/moFF/blob/5b48b239c2019c6dd2ec308f1e81bff2412e31b0/moff.py#L197)
in another [function](https://github.com/compomics/moFF/blob/5b48b239c2019c6dd2ec308f1e81bff2412e31b0/moff.py#L236) , I pass a new run object  rt interval [minpos, maxpos]
```
run_1 = pymzml.run.Reader(name,MS1_Precision=5e-6) 
for specpos in range(minpos, maxpos):
    # retrive the id of the RT interval 
   # contain all the spectra ID previously saved 
    specid = runid_list[specpos]
    try:
      spectrum = run[specid]
    except:
       pass
       print(specid)
```

**Comment by JB-MS** [comment]
It could be possible that retrieving the spectrum takes too long ing the try, except passage. Maybe you can check with another script how long it takes to retrieve the problematic spectra?

Which pymzML version do you use at the moment?

If you use a version >=2.0: To speed up access to single spectra, I strongly advise to use our igzip functionality, i.e. to use igzip the mzML files. This will work very fast and the file sizes are smaller. Maybe this will also circumvent the current problem.

To igzip mzML files you can use the example script [gzip_mzml.py](https://github.com/pymzml/pymzML/blob/master/example_scripts/gzip_mzml.py)
      

Cheers,
Johannes

**Comment by theoplatt** [comment]
Hi Johannes - I might have a similar problem. 

When I read a mzml file with 

`run = pymzml.run.Reader('/tmp/my.mzML')`

I can access spectrum up to about scan number 7000 instantly  with - 

`spectrum = run[1000]`

but 7000 and above is taking a very long time (longer than my patience at least!)

Does the code only load the first N scans into memory?

Thanks

Theo

**Comment by fu** [comment]
Hi there,

if retrieval takes that long, then that sounds like you are using a mzML that is either gzipped or does not have a index at the end of the file. The regular mzML index looks something like:
```
      <offset idRef="controllerType=0 controllerNumber=1 scan=44903">339880516</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=44904">339887758</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=44905">339897226</offset>
    </index>
    <index name="chromatogram">
      <offset idRef="TIC">339906348</offset>
    </index>
  </indexList>
  <indexListOffset>340505711</indexListOffset>
  <fileChecksum>ced0e4642762e4f4f0dc992b2dbac745e8d5b9ea</fileChecksum>
</indexedmzML>
```
[ tail -200 <mzML> should do the trick ]

So the solution would be:
a) If you need a packed mzML then I would suggest you use indexedGzip introduced in pymzML v2.0, then you can seek in gzipped files.
b) If you don't have an index then using pymzML v2.0 should solve your problem as well as it uses binary jumps inside the mzML to retrieve the spec quickly without the need of an index.

Hope that helps. If you have more issues, please post the mzML somewhere and we can have a look.

Cheers

.c

**Comment by theoplatt** [comment]
Thanks for getting back to me, Christian.

Here are the last few lines of the mzml file - they look similar to your example - 

````
      <offset idRef="controllerType=0 controllerNumber=1 scan=12029">1408428712</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12030">1408622379</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12031">1408828939</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12032">1409033422</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12033">1409239683</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12034">1409443336</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=12035">1409656891</offset>
    </index>
    <index name="chromatogram">
      <offset idRef="TIC">1409852800</offset>
    </index>
  </indexList>
  <indexListOffset>1410046578</indexListOffset>
  <fileChecksum>5695c58580266530a1d14125e4d6a9009ce5453e</fileChecksum>
</indexedmzML>
`````

I'm using the lastest code from the master branch (2.0.5) and here's what happens when I try and read a scan - 

````
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pymzml

In [2]: bsa_a_mzml = pymzml.run.Reader('/tmp/Lumos_Acquity_BSA_101718_01.mzML')

In [3]: bsa_a_mzml.info
Out[3]:
defaultdict(None,
            {'file_name': '/tmp/Lumos_Acquity_BSA_101718_01.mzML',
             'encoding': 'utf-8',
             'file_object': <pymzml.file_interface.FileInterface at 0x7f6e52afce80>,
             'offset_dict': {},
             'obo_version': '4.1.12',
             'mzml_version': '1.1.0',
             'referenceable_param_group_list': True,
             'referenceable_param_group_list_element': <Element '{http://psi.hupo.org/ms/mzml}referenceableParamGroupList' at 0x7f6e52afe368>,
             'run_id': 'Lumos_Acquity_BSA_101718_01',
             'start_time': '2018-10-17T20:16:51Z',
             'spectrum_count': 12035})

In [4]: bsa_a_mzml[1000]
Out[4]: <__main__.Spectrum object with native ID 1000 at 0x7f6e52afc278>

In [5]: bsa_a_mzml[5000]
Out[5]: <__main__.Spectrum object with native ID 5000 at 0x7f6e52a2ca58>

In [6]: bsa_a_mzml[7000]

````

(nothing after that final line)

I'm uploading the file to an S3 bucket and will share the link. 

Many thanks for looking into this

Theo

**Comment by theoplatt** [comment]
Here's a link to the file

[https://s3-us-west-2.amazonaws.com/seer-publictemp/Lumos_Acquity_BSA_101718_01.mzML](https://s3-us-west-2.amazonaws.com/seer-publictemp/Lumos_Acquity_BSA_101718_01.mzML)

I'll remove it after a few days. Thanks again!

**Comment by fu** [comment]
Hi Theo,

so I dl the file and it seems that the binary jumps are not quite optimal there. We have had developed another version. Let me find time to implement that within the next week or so.

**Comment by theoplatt** [comment]
Thanks Christian! Let me know if I can help run some tests on the new version.

**Comment by fu** [comment]
Hi theo,

Manuel and I updated the jump to a more "modern" version and you could checkout the binary_jump branch if you like. Alternatively we will be merging after a few more tests.

Cheers

.c

**Comment by theoplatt** [comment]
Thanks Christian - I'm trying that fix now. 

It's getting a lot further (and faster!) but I saw something odd that I don't know if you can reproduce with the same data file - 

`bsa_a_mzml[7245]`

fails on the first call with - 

> KeyError                                  Traceback (most recent call last)
> <ipython-input-10-3d54ef98935f> in <module>()
> ----> 1 spectrum = bsa_a_mzml[7245]
>       2 spectrum
> 
> /tmp/src/pymzml/pymzml/run.py in __getitem__(self, identifier)
>     167         except:
>     168             pass
> --> 169         spectrum = self.info['file_object'][identifier]
>     170         spectrum.calling_instance = self
>     171         if isinstance(spectrum, spec.Spectrum):
> 
> /tmp/src/pymzml/pymzml/file_interface.py in __getitem__(self, identifier)
>     106         # if type(self.offset_dict) == dict:
>     107         #     self.offset_dict.update(self.file_handler.offset_dict)
> --> 108         return self.file_handler[identifier]
>     109 
>     110 if __name__ == '__main__':
> 
> /tmp/src/pymzml/pymzml/file_classes/standardMzml.py in __getitem__(self, identifier)
>     113             )
>     114         else:
> --> 115             spectrum = self._binary_search(identifier)
>     116 
>     117         return spectrum
> 
> /tmp/src/pymzml/pymzml/file_classes/standardMzml.py in _binary_search(self, target_index)
>     477                         break
>     478 
> --> 479             start = self.offset_dict[target_index]
>     480             seeker.seek(start)
>     481             match = None
> 
> KeyError: 7245
> 

But if you run it directly again a second time it works.... 

Thanks

Theo

**Comment by fu** [comment]
Hi Theo,

is it still an issue with the latest version ? If so could you please upload the file again. Sorry, must have deleted it as well :)

Cheers

.c
