### ISSUE TITLE
Cannot Index mzML File, pymzml.utils.utils.index_gzip throws ValueError

### ISSUE THREAD

**Issue by mobiusklein** [pymzml/pymzML#103]
Attempting to run `pymzml.utils.utils.index_gzip` an mzML file throws an error when attempting to extract the native ID of a spectrum (`'controllerType=0 controllerNumber=1 scan=1'`) at line 60: 

https://github.com/pymzml/pymzML/blob/master/pymzml/utils/utils.py#L60

This appears to be because the call 
```python
int(regex_patterns.SPECTRUM_ID_PATTERN.search(
                        lineID
                    ).group(0))
```
matches the ID, but the regex pattern `="{0,1}([0-9]*)"{0,1}>{0,1}$`'s 0th group will be the matched substring itself, `'=1'`, not the first captured group, `'1'`. This results in trying to convert `"=1"` into an integer, which throws a `ValueError`.

This call originally worked because `regex_patterns.SPECTRUM_ID_PATTERN` used to be `[0-9]*$` where the only thing that was captured was numeric. This was changed to the current pattern in commit 5a6a8e0feb2c284d7e26ae492910082ad36867f8.

**Comment by fu** [comment]
@MKoesters could we revert that commit or at least the change Joshua pointed out ?

**Comment by MKoesters** [comment]
Yes, already looking into it

**Comment by MKoesters** [comment]
Should be fixed with #104

**Comment by mobiusklein** [comment]
Looks to have solved the problem.

**Comment by JB-MS** [comment]
Thanks for fixing this. I will make sure this important change makes it to PyPI today.
