### ISSUE TITLE
Error when working with ESI-ISO spectra

### ISSUE THREAD

**Issue by mukils15** [pymzml/pymzML#121]
The code I have written to average spectra works perfectly fine for the MS1 file that I have, but runs into an error for the MS2-ESI-ISO file. This is the error:

Traceback (most recent call last):
  File "C:\Users\Mukil\Documents\Python Scripts\average_multiprocessing_attempts.py", line 62, in <module>
    p.map(getSpectralAverageAndWriteToFile, [mzml_file1, mzml_file2])
  File "C:\Users\Mukil\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Mukil\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
KeyError: 3
>>>

Does anybody know if this is because of a difference in spectra structure for the MS2 file? Or perhaps know what exactly this error is saying and how to ge around it?

**Comment by MKoesters** [comment]
Hi and thanks for reporting this,

From this traceback, I cant tell you whats happening since the actual pymzML functionnality is probably implemented in your getSpectralAverageAndWriteToFile function.
Could you post that code (if possible) or tell me which pymzML function calls you are using?
Also, could you supply on spectrum XML element from your MS2 file?
The binary data can be stripped out, if you do not want to disclose your data.
Sadly, I'll have a lot on my plate currently and I'm on the road a lot, but I hope I can have a look at this on the weekend or the beginning of next week.

Best,
Manuel

**Comment by mukils15** [comment]
Hi, thank you! Here is the code:

def getSpectralAverageAndWriteToFile(filepath):
    msrun = pymzml.run.Reader(filepath, MS1_Precision=5e-6, MSn_Precision=20e-6)
    # Get length of any one spectrum
    spec_length = len(msrun[2].mz)
    print(spec_length)

    # initialize list to hold averages
    total_i = [0] * spec_length

    # initialize var to count number of spectra in file
    numspectra = 0

    # compute number of spectra in file and store total intensity at each point in single list
    msrun2 = pymzml.run.Reader(filepath, MS1_Precision=5e-6, MSn_Precision=20e-6)
    for spectrum in msrun2:
        numspectra += 1
        x = 0
        while x < spec_length:
            total_i[x] = total_i[x] + spectrum.i[x]
            x += 1

    # debug print
    print(numspectra)

    # compute average intensity at each point across all spectra
    avg_i = [item / numspectra for item in total_i]
    mz_i_tuples = list(zip(spectrum.mz, avg_i))
    # print (mz_i_tuples)
    plt.plot(spectrum.mz, avg_i)
    plt.xlabel("m/z")
    plt.ylabel('Intensity')

    # write spectra to another file

    plt.savefig(filepath + ' .png')

And here is a spectrum with the binary data stripped out:

<spectrum index="1" id="scan=2" defaultArrayLength="6001">
          <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="3"/>
          <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" value=""/>
          <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="MS3-ETD-CID.2.2. File:&quot;&quot;, NativeID:&quot;scan=2&quot;"/>
          <scanList count="1">
            <cvParam cvRef="MS" accession="MS:1000795" name="no combination" value=""/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="3.888" unitCvRef="UO" unitAccession="UO:0000010" unitName="second"/>
              <scanWindowList count="1">
                <scanWindow>
                  <cvParam cvRef="MS" accession="MS:1000501" name="scan window lower limit" value="250.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000500" name="scan window upper limit" value="1000.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </scanWindow>
              </scanWindowList>
            </scan>
          </scanList>
          <precursorList count="1">
            <precursor>
              <isolationWindow>
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="518.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              </isolationWindow>
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="518.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000133" name="collision-induced dissociation" value=""/>
              </activation>
            </precursor>
          </precursorList>
          <binaryDataArrayList count="2">
            <binaryDataArray encodedLength="12200">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" value="" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              <binary></binary>
            </binaryDataArray>
            <binaryDataArray encodedLength="776">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" value="" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
              <binary></binary>
            </binaryDataArray>
          </binaryDataArrayList>
        </spectrum>

Thank you in advance.

**Comment by mukils15** [comment]
And here is one spectra, with binary data stripped:

<spectrum index="1" id="scan=2" defaultArrayLength="6001">
          <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="3"/>
          <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" value=""/>
          <cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="MS3-ETD-CID.2.2. File:&quot;&quot;, NativeID:&quot;scan=2&quot;"/>
          <scanList count="1">
            <cvParam cvRef="MS" accession="MS:1000795" name="no combination" value=""/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="3.888" unitCvRef="UO" unitAccession="UO:0000010" unitName="second"/>
              <scanWindowList count="1">
                <scanWindow>
                  <cvParam cvRef="MS" accession="MS:1000501" name="scan window lower limit" value="250.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000500" name="scan window upper limit" value="1000.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </scanWindow>
              </scanWindowList>
            </scan>
          </scanList>
          <precursorList count="1">
            <precursor>
              <isolationWindow>
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="518.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              </isolationWindow>
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="518.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000133" name="collision-induced dissociation" value=""/>
              </activation>
            </precursor>
          </precursorList>
          <binaryDataArrayList count="2">
            <binaryDataArray encodedLength="12200">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" value="" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              <binary></binary>
            </binaryDataArray>
            <binaryDataArray encodedLength="776">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" value="" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
              <binary></binary>
            </binaryDataArray>
          </binaryDataArrayList>
        </spectrum>

**Comment by MKoesters** [comment]
Hi,
I had a quick look at your spectrum and it seems to be an MS3 scan, not MS2.
Can you try to initialize the reader as the following:
msrun = pymzml.run.Reader(
    filepath,
    MS1_Precision=5e-6,
    MSn_Precision=20e-6,
    MS_precisions={3:20e-6}
)
Alternatively:
msrun = pymzml.run.Reader(
    filepath,
    MS_precisions={1:5e-6, 2:20e-6, 3:20e-6}
)
instead of 20e-6 in the dict, just use your ms3 precision.

I hope this fixes it. If you can confim it works, I'll push a fix that makes your approach work asap.

Best,
Manuel

**Comment by mukils15** [comment]
Hi,
Your fix worked perfectly, thank you so much! What exactly does initializing the reader in that fashion do as opposed to what I had originally?

Sincerely,
Mukil Shanmugam

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MKoesters** [comment]
MS_Precisions is a dict where the key represents your MS level and the value the precision.
This way, you can set precisions for every MS level you like using custom values.
The precision is required for transforming the mz values and for finding peaks for example.

Setting MSn_Precisions was buggy since it only set MS2 precision, not MS3 as in your file.
However I'll merge my pull request to also set MS3 precision when setting MSn_Precision.
So your first approach should work also, would be nice if you could confirm that.

Best,
Manuel
