### ISSUE TITLE
Remove warning to install ms_deisotope

### ISSUE THREAD

**Issue by michaelmarty** [pymzml/pymzML#157]
I am using pymzml in another deconvolution python package. Can you remove the warning to install ms_deisotope when pymzml is imported? My users are probably going to be confused by the additional warning. I would suggest instead that it prints an error if ms_deisotope is not installed when you try to run it. Thanks!

**Comment by MKoesters** [comment]
Hi,

just created a pull request to print this warning only the first time _deconvolute_peaks() is used.
Sry for the inconvenience, I'll merge the pull request this evening.

Best,
Manuel

**Comment by michaelmarty** [comment]
Thanks, Manuel! I don't mind waiting for a new pypi release. I've fixed my local version. I think most users use the compiled version I build with PyInstaller, so fixing it locally should be fine for now. But, I appreciate not having to comment it out every time I update pymzml. Thanks, again! It's a fantastic package!
