### ISSUE TITLE
Add a feature to read ion current file(dispersion filed matrix file) 

### ISSUE THREAD

**Issue by kothawadegs** [pymzml/pymzML#184]
Please add .df file reader to analyse the dispersion field matrix data. I tried to read using the function "pymzml.run.Reader(file)", but it's throwing an error. Please find attached for reference  Screenshots. 
<img width="749" alt="error1" src="https://user-images.githubusercontent.com/8245778/65283442-fee37500-daeb-11e9-93c4-64a1a567523d.PNG">
<img width="756" alt="error2" src="https://user-images.githubusercontent.com/8245778/65283443-ff7c0b80-daeb-11e9-9d63-5ba90da59767.PNG">

**Comment by MKoesters** [comment]
Hi @kothawadegs ,

Could you give me some more information about the file you are using?
It is a mzML file right?
If so, could you upload an example so I could test why it does not work?
Additionally, I don't really know what you mean with dispersion field matrix and where/how it is stored, could you give me some more information or a link to make this clearer?

Best,
Manuel

**Comment by kothawadegs** [comment]
Hi @MKoesters ,

It's not a mzML file. It's dispersion field file generated by FAIMS system. 
Please find attached file in the zip folder. 
[matrix_0001.zip](https://github.com/pymzml/pymzML/files/3637651/matrix_0001.zip)
Please let me know whether it is possible to read and process such file using pymzML. 

Regards,
Gajanan

**Comment by StSchulze** [comment]
While it would be great to add a feature that allow reading of dispersion field/ion mobility data, pymzML is specifically designed to read mzML files and it seems like the field has not yet adopted this standard file format in a way that allows an easy integration of ion mobility data.
The workaround that seems to be most commonly used (from what I could find with a quick search) is to split the raw file into multiple mzML, one for each CF. (e.g.: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6145172/).

**Comment by MKoesters** [comment]
As Stefan said, pymzML is specifically designed for handling mzML files.

However I'd appreciate feedback, if you happen to to convert your .df file to mzML and use pymzML.
Since I never seen an mzML generated from a .df file, a small example would help to make sure pymzML can handle these.

I'm closing this for now, if you run into problems with mzMLs generated from .df, feel free to open a new issue :)
