### ISSUE TITLE
Negative m/z values

### ISSUE THREAD

**Issue by ajmazurie** [pymzml/pymzML#20]
Hi,
I am not sure if this is a bug or the result of my misunderstanding of the mzML format. When I list all m/z and intensities in a given spectrum using the underlying code I usually get a sensible range for m/z; e.g., from 40 to 1000:

```python

for spectrum in in pymzml.run.Reader(...):
    if (spectrum.get("scan time") is None):
        continue
    for mz, intensity in spectrum.centroidedPeaks:
        print(spectrum_idx, mz, intensity)
```

However with some other files generated from the same instrument and on the same samples (but at different times) I get negative and positive values way outside of this range; e.g., -5287 and +218039.

I could of course filter out those, but I'd like to ensure there is not something wrong either with the underlying mzML file or the way pymzML is parsing it. Is there an explanation to negative m/z values?

Best,
Aurelien

**Comment by fu** [comment]
This was dealt with, right Aurélien ?
