### ISSUE TITLE
Support for VITEK MS (aka. Shimadzu Assurance)

### ISSUE THREAD

**Issue by frederic-foucault** [pymzml/pymzML#216]
Dear all,

i'm having problems to read SOME not all mzml files.

I have python version 3.7.4installed on osx catalina
I installed pymzml version 2.4.6

```

for my_file in os.listdir(data_in):
    if my_file.endswith('mzml'):
        # parse mzml
        run = pymzml.run.Reader(os.path.join(data_in,my_file))

```
The error is:

```
Traceback (most recent call last):
  File "/usr/src/app/src/mzml converter v0.001.py", line 34, in <module>
    run = pymzml.run.Reader(os.path.join(data_in,my_file))
  File "/usr/local/lib/python3.7/dist-packages/pymzml/run.py", line 116, in __init__
    self.info["file_object"] = self._open_file(path_or_file)
  File "/usr/local/lib/python3.7/dist-packages/pymzml/run.py", line 218, in _open_file
    build_index_from_scratch=self.build_index_from_scratch,
  File "/usr/local/lib/python3.7/dist-packages/pymzml/file_interface.py", line 27, in __init__
    self.file_handler = self._open(path)
  File "/usr/local/lib/python3.7/dist-packages/pymzml/file_interface.py", line 58, in _open
    path_or_file, self.encoding, self.build_index_from_scratch
  File "/usr/local/lib/python3.7/dist-packages/pymzml/file_classes/standardMzml.py", line 59, in __init__
    self.seek_list = self._read_extremes()
  File "/usr/local/lib/python3.7/dist-packages/pymzml/file_classes/standardMzml.py", line 669, in _read_extremes
    re.search(b"[0-9]*$", id_match.group("id")).group()
ValueError: invalid literal for int() with base 10: b''
```

Thank you for your help
Best regards
Frederic Foucault

**Comment by MKoesters** [comment]
Hi Frederic,
thanks for reporting this Issue.
Would it be possible to upload your mzML file?
Also, is there anything different about the mzML files which won't load, e.g. the runs were measured on a different machine or something like that?

Best,
Manuel

**Comment by frederic-foucault** [comment]
Hi Manuel,

here is the line i found in the mzml fle:
<spectrum index="0" id="v1v6232d" defaultArrayLength="117">

I need more informations to be able to find the content of the id or a sample.

Best
Frederic

**Comment by frederic-foucault** [comment]
<spectrum index="0" id="v1v6232d" defaultArrayLength="117">

**Comment by frederic-foucault** [comment]
Hi Manuel
here is the line
<spectrum index="0" id="v1v6232d" defaultArrayLength="117">

**Comment by MKoesters** [comment]
What you posted is enough for me, I can see why its not working.
Just out of curiosity, can you also send me the same line fom a file that is working?
And do you know, on what instrument the run was measure and which conversion software you used?

I'll report back to you as soon as I have fix for your problem

**Comment by frederic-foucault** [comment]
Hello Manuel

Attached is the mzml file

Thank you very much for your help

Best
Frederic

**Comment by frederic-foucault** [comment]
Hello Manuel

it was a VITEK MS (aka. Shimadzu Assurance). Software used is the Biomerieux VITEK MS Software. It contains masslists and processed data.

Best
Frederic

**Comment by MKoesters** [comment]
Hi Frederic,

I started to implement a fix for your problem, could you install pymzml using:
`pip install "git+https://github.com/pymzml/pymzml.git@fix_216"` and tell me if this works for you?

**Comment by frederic-foucault** [comment]
Hello Manuel

I run the command and get  Same error as before ☹.  Here is the output of the installation of the pymzml fix.
I’m not sure that it was really installed on top of the pymzml 2.4.6……?

Best
frederic
[A screenshot of a cell phone  Description automatically generated]

**Comment by MKoesters** [comment]
Hmm, okay, I tried to create a similar mzML as you have, maybe I missed something ...
So, attaching files to your mails when answering here does not work it seems, would you be able to upload the mzML either to gdrive and share the link with me or use a file hoster like https://wetransfer.com/?

Also, are installaing pymzML globally or a you using virtual environments (https://docs.python.org/3/tutorial/venv.html)?
If you are using virtualenvironments, could you test the command above with a fresh environment?

**Comment by frederic-foucault** [comment]
Please give me an email address because this : Manuel notifications@github.com<mailto:notifications@github.com> does not seems to work in wetransfer

**Comment by frederic-foucault** [comment]
Concerning installation of pymzml i have created a virtual environment using anaconda. This virtual environment is having python version 3.6

From: Foucault Frederic <frederic.foucault@mabritec.com>
Date: Tuesday, 31 March 2020 at 15:59
To: pymzml/pymzML <reply@reply.github.com>, pymzml/pymzML <pymzML@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [pymzml/pymzML] Error run.reader ValueError: invalid literal for int() with base 10: b'' (#216)

Please give me an email address because this : Manuel notifications@github.com<mailto:notifications@github.com> does not seems to work in wetransfer

**Comment by MKoesters** [comment]
you can send the file to manuel.koesters@dcb.unibe.ch
Sry for the inconvenience, I never worked with files from the instrument you are working with and thus never tested pymzML with these kinds of files

**Comment by MKoesters** [comment]
Thanks, I received and tested your file.
However, I can open it with the fixed version and acces the spectra including mz and intensity values
Did you test the code above and can verify that the output is as expected?
I also created an fresh virtualenvironment (I'm not using conda though) and run the following code
```
$ pip install "git+https://github.com/pymzml/pymzml.git@fix_216"
$ ipython
In [1]: import pymzml                                                                        
In [2]: run = pymzml.run.Reader("/home/manuel/Downloads/1585556427714_19-03-28_Triemli_v1v6232d_1_DS184019882_K4_6393_1.mzml", build_index_from_scratch=True)                                  
[ Warning ] Found 1 spectra and 0 chromatograms
[ Warning ] However Spectrum index list shows 0 and Chromatogram index list shows 0 entries
[ Warning ] Updating offset dict with found offsets but some might be still missing
[ Warning ] This may happen because your is file truncated

In [3]: s = run['v1v6232d']                                                                                                                                                                    

In [4]: s.peaks('raw') 
```
which worked for me

**Comment by frederic-foucault** [comment]
Hello Manuel

It works for me too (created a venv , install the updated version of pymzml , read the mzml file).

Thank you very much Manuel. I may have a few more questions later on.
Best
Frederic Foucault

**Comment by MKoesters** [comment]
Great to hear that!
I'll do some further testing and then merge this branch to dev and upload a version to pypi
When this happens, I'll let you know

Btw, I also implemented a property for you to access the signal_to_noise array
`run['v1v6232d'].signal_to_noise`

**Comment by frederic-foucault** [comment]
Thank you very much Manuel. This is great. I really appreciate you give us access to the signal to noise ratio on top of it.
I knew that theses mzml files were not raw but processed data. Could you tell me what was specific to these files compared to others ?
I’m look forward installing this new release…

Best
Frederic Foucault

**Comment by frederic-foucault** [comment]
Thank you manuel !
