### ISSUE TITLE
Spectrum.scan_time_in_minutes() can be wrong

### ISSUE THREAD

**Issue by leonweber** [pymzml/pymzML#231]
Spectrum.scan_time_in_minutes() produces wrong values if called multiple times

```python
specs[0].scan_time_in_minutes()
Out[2]: 5.4814814814814815e-06
specs[0].scan_time_in_minutes()
9.135802469135803e-08
```

This is probably because the casting (e.g. from seconds to minute) is applied repeatedly.

**Comment by MKoesters** [comment]
Hi,

thanks for reporting this!
I fixed the issue and we will upload a new release during this week

Best,
Manuel
