### ISSUE TITLE
pymzml/obo/psi-ms-* are executable

### ISSUE THREAD

**Issue by lopippo** [pymzml/pymzML#238]
Greetings,

I found that a large subset of the files in pymzml/obo/psi-ms-* have their executable bit set. These are gzipped files (.gz) and I was wondering if there is an explanation for this. We cannot ship the files with the executable bit set if they are not real script files or actual executable binary images. I plan to reset the exec bit for these files. This is ok, right ?

Edit: the python3/dist-packages/pymzml/version.txt file is also executable.

Thank you for your attention,
Sincerely,
Filippo

**Comment by MKoesters** [comment]
Hi Filippo,

that must have happened by accident, at least I don't see a reason why it should be like that, removing the exec bit is a good idead I guess, thanks for pointing that out.

Best,
Manuel

**Comment by lopippo** [comment]
Greetings, Manuel,
That's fine, then. Please, fix that for later versions.
Thanks again, closing the issue now.
Sincerely,
Filippo
