### ISSUE TITLE
Division with zero error 

### ISSUE THREAD

**Issue by Aviral3364** [pymzml/pymzML#248]
Dear all,

I am using package pymzml but one problem appeared with some mzml files although same files are running in other languages. I am trying to open mzml file with this commands:

path = file1.mzml
run = pymzml.run.Reader(path)

![Screenshot (93)](https://user-images.githubusercontent.com/54510266/89093603-9cc8f100-d3d9-11ea-93f7-ee722a420adf.png)

Can anyone has idea why is it happening with some mzml files.

Best regards,
Aviral Singh

**Comment by MKoesters** [comment]
Hi Aviral,

Which version of pymzML are you using?
Also, can you tell me if your mzML file has an index and if yes, how it looks like?
When I have this info, I'll be able to help you better

In the mean time, does initializing the readder with `build_index_from_scratch=True` change anything?

Best,
Manuel

**Comment by Aviral3364** [comment]
Hi Manuel,

Thanks for the concern on this issue. 
pymzML version = 2.4.7
mzML file has the index and I have also tried build_index_from_scratch=True but the problem still not solved. You can look into the mzML file by going through this link: [https://drive.google.com/drive/folders/16y9dVuyx8hGMS5DlhFl18zuHwYnD_0Yy?usp=sharing](url)

**Comment by MKoesters** [comment]
Could you try to install https://github.com/pymzml/pymzML/tree/fix/%23248 by

`pip install 'git+https://github.com/pymzml/pymzml.git@fix248'`

Best,
Manuel

**Comment by Aviral3364** [comment]
I tried with the link and the error is removed. Thanks for the amendments.

Regards,
Aviral Singh
