### ISSUE TITLE
Got Problem Installing requirements.txt

### ISSUE THREAD

**Issue by weantony** [pymzml/pymzML#253]
Hi Everyone,

I am a beginner in python. I got some problem in installing requirements.txt file. Could someone give some advice please? The entile code is listed below. It looks like there are two errors. The first one is failed to build wheel for pynumpress and the second one is failed to run setup.py for pynumpress. I did have installed visual studio 2019 and wheel already. 

Thank you very much in advance.

```
C:\Users\weant\Downloads\pymzML-dev\pymzML-dev>python -m pip install -r requirements.txt
Requirement already satisfied: numpy in c:\users\weant\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 2)) (1.19.2)
Requirement already satisfied: plotly==4.8.1 in c:\users\weant\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (4.8.1)
Collecting pynumpress==0.0.5
  Using cached pynumpress-0.0.5.tar.gz (110 kB)
Collecting regex
  Using cached regex-2020.10.28-cp38-cp38-win_amd64.whl (269 kB)
Processing c:\users\weant\appdata\local\pip\cache\wheels\e5\8e\42\3fa7e28313ea33a41260140e9cb96cff3c2c7fc334eb6dbb45\ms_deisotope-0.0.14-py3-none-any.whl
Requirement already satisfied: six in c:\users\weant\appdata\roaming\python\python38\site-packages (from plotly==4.8.1->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in c:\users\weant\appdata\local\programs\python\python38\lib\site-packages (from plotly==4.8.1->-r requirements.txt (line 3)) (1.3.3)
Processing c:\users\weant\appdata\local\pip\cache\wheels\93\7f\7d\78ec535a4340ef2696aad8b17fe8bb063d56301bd62881b069\dill-0.3.2-py3-none-any.whl
Collecting pyteomics>=4.0
  Using cached pyteomics-4.3.3-py2.py3-none-any.whl (186 kB)
Collecting psims>=0.1.28
  Using cached psims-0.1.31-py3-none-any.whl (10.7 MB)
Collecting ms-peak-picker
  Using cached ms_peak_picker-0.1.29-cp38-cp38-win_amd64.whl (1.6 MB)
Collecting scipy
  Using cached scipy-1.5.3-cp38-cp38-win_amd64.whl (31.4 MB)
Collecting lxml
  Using cached lxml-4.6.1-cp38-cp38-win_amd64.whl (3.5 MB)
Collecting brain-isotopic-distribution
  Using cached brain_isotopic_distribution-1.5.4-cp38-cp38-win_amd64.whl (640 kB)
Collecting sqlalchemy
  Using cached SQLAlchemy-1.3.20-cp38-cp38-win_amd64.whl (1.2 MB)
Building wheels for collected packages: pynumpress
  Building wheel for pynumpress (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\weant\AppData\Local\Temp\pip-wheel-g2dpb_o3'
       cwd: C:\Users\weant\AppData\Local\Temp\pip-install-urev8ft6\pynumpress\
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pynumpress
  copying pynumpress\__init__.py -> build\lib.win-amd64-3.8\pynumpress
  running build_ext
  building 'pynumpress.pynumpress' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\pynumpress
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppynumpress/pynumpress.cpp /Fobuild\temp.win-amd64-3.8\Release\pynumpress/pynumpress.obj /EHsc
  pynumpress.cpp
  pynumpress/pynumpress.cpp(30): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pynumpress
  Running setup.py clean for pynumpress
Failed to build pynumpress
Installing collected packages: pynumpress, regex, dill, pyteomics, lxml, sqlalchemy, psims, scipy, ms-peak-picker, brain-isotopic-distribution, ms-deisotope
    Running setup.py install for pynumpress ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\weant\AppData\Local\Temp\pip-record-w891_sz1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\weant\AppData\Local\Programs\Python\Python38\Include\pynumpress'
         cwd: C:\Users\weant\AppData\Local\Temp\pip-install-urev8ft6\pynumpress\
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pynumpress
    copying pynumpress\__init__.py -> build\lib.win-amd64-3.8\pynumpress
    running build_ext
    building 'pynumpress.pynumpress' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\pynumpress
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppynumpress/pynumpress.cpp /Fobuild\temp.win-amd64-3.8\Release\pynumpress/pynumpress.obj /EHsc
    pynumpress.cpp
    pynumpress/pynumpress.cpp(30): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-urev8ft6\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\weant\AppData\Local\Temp\pip-record-w891_sz1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\weant\AppData\Local\Programs\Python\Python38\Include\pynumpress' Check the logs for full command output.
```

**Comment by StSchulze** [comment]
Hi weantony,

you can try to install the packages individually to see if that solves it, even though it's fairly unlikely:
`pip install numpy`
Installing numpy first and then pynumpress makes sense I think
`pip install pynumpress`
Installing pynumpress without the version specified may help as well.
But in the end it looks mostly like a Windows issue and I'm not sure how to fix that.
Maybe someone else has a idea?

**Comment by JB-MS** [comment]
Hi weantony,

may be related to the the PATH variable, which has to be edited.

Chekc this out: https://stackoverflow.com/questions/48091017/c1083-cannot-open-include-file-python-h-no-such-file-or-directory

Cheers,
Johannes

**Comment by weantony** [comment]
> Hi weantony,
> 
> you can try to install the packages individually to see if that solves it, even though it's fairly unlikely:
> `pip install numpy`
> Installing numpy first and then pynumpress makes sense I think
> `pip install pynumpress`
> Installing pynumpress without the version specified may help as well.
> But in the end it looks mostly like a Windows issue and I'm not sure how to fix that.
> Maybe someone else has a idea?

Hi StSchulze

Thank you very much for your suggestion. I tried to install pynum and pynumpress seperately. I think the problem comes from installing pynumpress. The error message listed below is what I got from installing pynumpress. It looks quite similar to what I got from installing requirements.txt. However, I am still trying to figure out what the problem is.


C:\Users\weant>python -m pip install pynumpress
Collecting pynumpress
  Using cached pynumpress-0.0.5.tar.gz (110 kB)
Requirement already satisfied: numpy in c:\users\weant\appdata\roaming\python\python38\site-packages (from pynumpress) (1.19.2)
Building wheels for collected packages: pynumpress
  Building wheel for pynumpress (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\weant\AppData\Local\Temp\pip-wheel-2kqpjacb'
       cwd: C:\Users\weant\AppData\Local\Temp\pip-install-y79a4pyb\pynumpress\
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pynumpress
  copying pynumpress\__init__.py -> build\lib.win-amd64-3.8\pynumpress
  running build_ext
  building 'pynumpress.pynumpress' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\pynumpress
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\pynumpress -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppynumpress/pynumpress.cpp /Fobuild\temp.win-amd64-3.8\Release\pynumpress/pynumpress.obj /EHsc
  pynumpress.cpp
  pynumpress/pynumpress.cpp(30): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pynumpress
  Running setup.py clean for pynumpress
Failed to build pynumpress
Installing collected packages: pynumpress
    Running setup.py install for pynumpress ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\weant\AppData\Local\Temp\pip-record-pn4i6w2m\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\weant\AppData\Local\Programs\Python\Python38\Include\pynumpress'
         cwd: C:\Users\weant\AppData\Local\Temp\pip-install-y79a4pyb\pynumpress\
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pynumpress
    copying pynumpress\__init__.py -> build\lib.win-amd64-3.8\pynumpress
    running build_ext
    building 'pynumpress.pynumpress' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\pynumpress
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\pynumpress -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include -IC:\Users\weant\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppynumpress/pynumpress.cpp /Fobuild\temp.win-amd64-3.8\Release\pynumpress/pynumpress.obj /EHsc
    pynumpress.cpp
    pynumpress/pynumpress.cpp(30): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\weant\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\weant\\AppData\\Local\\Temp\\pip-install-y79a4pyb\\pynumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\weant\AppData\Local\Temp\pip-record-pn4i6w2m\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\weant\AppData\Local\Programs\Python\Python38\Include\pynumpress' Check the logs for full command output.

**Comment by StSchulze** [comment]
Hi,

have you tried the suggestion of @JB-MS ?
If that doesn't work either, you might want to open an issue in the pynumpress repo directly. I'm tagging @mobiusklein in case he has a quick fix for it?

Best,
Stefan

**Comment by mobiusklein** [comment]
I haven't encountered this problem on Windows before. It looks like the include path is being specified correctly, but let's check. If you go to `C:\Users\weant\AppData\Local\Programs\Python\Python38\include`, do you see the file `Python.h` in that folder?

**Comment by weantony** [comment]
> Hi,
> 
> have you tried the suggestion of @JB-MS ?
> If that doesn't work either, you might want to open an issue in the pynumpress repo directly. I'm tagging @mobiusklein in case he has a quick fix for it?
> 
> Best,
> Stefan

Hi StSchulze,

Thank you very much for the reply. I am really sorry I am not able to make very quick reponse because my knowledge related to programing and CS is very limited. I tried to read the suggestion of JB-MS, but I honestly still can't understand the contend of it. Instead I tried to installed python and visual studio 2019 in the same way on another laptop with win 10 Enterprise. After trying pip install install -r requirements.txt, the error became Preparing wheel metadata... error. But pynumpress was successfully installed. So I guess the problem why I can't install pynumpress is related to certain setting or path somewhere. I am still trying to figure things out.

Thank you very much for reaching out and help.

**Comment by weantony** [comment]
> I haven't encountered this problem on Windows before. It looks like the include path is being specified correctly, but let's check. If you go to `C:\Users\weant\AppData\Local\Programs\Python\Python38\include`, do you see the file `Python.h` in that folder?

Hi mobiusklein,

I didn't even find a filefolder named inclue in C:\Users\weant\AppData\Local\Programs\Python\Python38.  I can find this folder and python.h on my other labtop which install python. Do I need to remove and install python on my pc or just add something to it please? Thank you very much for reaching out and help.

**Comment by mobiusklein** [comment]
I've just uploaded a Python 3.8 Windows wheel for `pynumpress`, so you should be able to install that at least without needing to make any changes to your system now.

That you can't find `C:\Users\weant\AppData\Local\Programs\Python\Python38\include` explains why building `pynumpress` failed. I can't imagine why the folder would be missing, either. In theory, you could just copy over the include folder from another known good copy of Python 3.8, but this assumes no other part of your Python installation is unexpectedly missing.

The `include` folder isn't necessary unless you need to install a package with a C extension from source again, like you're trying to do with `pynumpress`.

**Comment by weantony** [comment]
> I've just uploaded a Python 3.8 Windows wheel for `pynumpress`, so you should be able to install that at least without needing to make any changes to your system now.
> 
> That you can't find `C:\Users\weant\AppData\Local\Programs\Python\Python38\include` explains why building `pynumpress` failed. I can't imagine why the folder would be missing, either. In theory, you could just copy over the include folder from another known good copy of Python 3.8, but this assumes no other part of your Python installation is unexpectedly missing.
> 
> The `include` folder isn't necessary unless you need to install a package with a C extension from source again, like you're trying to do with `pynumpress`.

Hi mobiusklein,

Thank you so much. I tried python -m pip install pynumpress again and nothing changed. But I think I should reinstall the python first to make it right first. I'll let you know if there's any progress on that. Thank you so much for your help.

**Comment by weantony** [comment]
> I've just uploaded a Python 3.8 Windows wheel for `pynumpress`, so you should be able to install that at least without needing to make any changes to your system now.
> 
> That you can't find `C:\Users\weant\AppData\Local\Programs\Python\Python38\include` explains why building `pynumpress` failed. I can't imagine why the folder would be missing, either. In theory, you could just copy over the include folder from another known good copy of Python 3.8, but this assumes no other part of your Python installation is unexpectedly missing.
> 
> The `include` folder isn't necessary unless you need to install a package with a C extension from source again, like you're trying to do with `pynumpress`.

Hi mobiusklein,

I have reinstalled python 3.8.0 and include filefolder showed up. The installation of requirements.txt and setup.py are successfully finished. Thank you very much for all your kindness help. May I further ask what does tox mean in test the package and correct installation please? It seems the tox file in pymzML could not just run by python code.
Thank you again for your help.

**Comment by mobiusklein** [comment]
Happy to help.

`tox` is a tool for testing automating testing Python programs across multiple Python versions/environments. It's useful for proving that the program. I don't think you need to worry about it for the moment, unless you plan to make substantial changes to pymzML itself.

**Comment by weantony** [comment]
> Happy to help.
> 
> `tox` is a tool for testing automating testing Python programs across multiple Python versions/environments. It's useful for proving that the program. I don't think you need to worry about it for the moment, unless you plan to make substantial changes to pymzML itself.

Thank you very much again.

**Comment by MKoesters** [comment]
Hi @weantony,

Is your problem resolved and can we close this issue?
And Thanks @mobiusklein for fixing this so fast again!

Best,
Manuel

**Comment by weantony** [comment]
> Hi @weantony,
> 
> Is your problem resolved and can we close this issue?
> And Thanks @mobiusklein for fixing this so fast again!
> 
> Best,
> Manuel


Hi MKoester,

Thank you all very much, the problem is resolved and can be closed. Your effort really helped a lot.

Best Regards,
Jian Yu
