### ISSUE TITLE
Cannot get precursor information from MS3 spectra

### ISSUE THREAD

**Issue by lummyk** [pymzml/pymzML#254]
Hi! Thank you for this software--it's been tremendously useful for my work.

**Describe the bug**
Cannot get precursor information from Spectrum object.

**To Reproduce**

```
import pymzml
run = pymzml.run.Reader('KL-NB1-12_A.mzML', MS_precisions={1: 1e-6, 2: 1e-6, 3: 1e-6})
# get some spectrum, ms3, with MS level == 3
ms3.precursors
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-25a2f3d1799b> in <module>
----> 1 ms3.precursors

/usr/local/miniconda3/lib/python3.8/site-packages/pymzml/spec.py in precursors(self)
    169             precursor(list): list of precursor ids for this spectrum.
    170         """
--> 171         if self._precursors is None:
    172             precursors = self.element.findall(
    173                 "./{ns}precursorList/{ns}precursor".format(ns=self.ns)

AttributeError: 'Spectrum' object has no attribute '_precursors'
```

**Expected behavior**
spectrum.precursors should return a list of SpectrumRef ids.

**Desktop (please complete the following information):**
 - OS: Linux 5.4.0-53-generic #59-Ubuntu SMP x86_64 GNU/Linux

**Additional context**
It appears that the issue is self._precursors is never initialized in the Spectrum class. Adding
`self._precursors = None` appears to fix.

**Comment by StSchulze** [comment]
Hi lummyk,

Thanks for using pymzML, I'm glad it's helpful for your work!

@MKoesters will probably be able to tell you more details, but in principle there are two spectrum properties `precursors `and `selected_precursors`
You are right that precursors does not get initialized, while selected_precursors does. The latter also checks for the correct ontology terms (MS:1000744, etc.).
So, I think you probably want to use `selected_precursors` instead of `precursors` and that should hopefully solve your issue (I can't test it for MS3 right now, but for MS2 it does).

Best,
Stefan

**Comment by JB-MS** [comment]
`spectrum.precursors `gives you a list of spectrum IDs from which the ion was isolated, `spectrum.selected_precursors` gives you the isolated m/z values, intensities and charges.

Actually, `spectrum._precursors` is not set, which causes the error.

@lummyk You can open a pull request with that particular change if you like.

**Comment by lummyk** [comment]
Thank you @JB-MS, @StSchulze, @MKoesters for the answers and the pull request.

I guess my post should've been more accurately titled "cannot get spectrum ID" instead. I was indeed able to access the m/z, intensity, and charge using `spectrum.selected_precursors`.

Best,
Kenneth

**Comment by MKoesters** [comment]
Hi @lummyk,

Sorry this took so long, we decided it would be much better to put the precursor id into `selected_precursors` and get rid of `precursors` altogether.
This was sort of a legacy code situtation.

I hope this does not cause too much trouble for you, if it does, we could also talk about leaving `precursors` in for some time but print a one time deprecation warning.

Best,
Manuel

**Comment by lummyk** [comment]
Hi @MKoesters,

No worries and sorry I didn't check back sooner. Your solution (`selected_precursors`) is much cleaner and it's no trouble for me at all. Happy new year and thanks again for this excellent tool!

Best,
Kenneth
