### ISSUE TITLE
ZeroDivisionError: division by zero 

### ISSUE THREAD

**Issue by EightForest** [pymzml/pymzML#279]
Hello,
**Describe the bug**
I am using package pymzml but one problem appeared .
I am trying to open mzml file with this commands:

run = pymzml.run.Reader("F:\\DEC-YYH\\0106\\DecoSWATH\\ms1_data_translate\\B-NEG-1.mzML")

But unfortunately I receive this error:
![image](https://user-images.githubusercontent.com/90665001/134838295-a71ec75d-efab-4861-9fb5-f18e1c1fdfac.png)

**To Reproduce**
import pymzml
run = pymzml.run.Reader("F:\\DEC-YYH\\0106\\DecoSWATH\\ms1_data_translate\\B-NEG-1.mzML")

**Expected behavior**
Should be no warning, or warning on first use.

**Screenshots**
![image](https://user-images.githubusercontent.com/90665001/134838846-6a139d0b-b156-4127-a17c-4e01b945e970.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version python 3.6.8

**Comment by StSchulze** [comment]
Hi Yin Yinghao,

Which version of pymzML are you using?

This issue should have been solved by #249 , so maybe try updating your pymzML version, using e.g.:
`pip install pymzml==2.5.0`

Let us know if that helps.

**Comment by MKoesters** [comment]
Hi Yin Yinghao,

Did this resolve your issue and can we close this PR?

Best,
Manuel
