### ISSUE TITLE
Upgrade PyPI to 0.7.6

### ISSUE THREAD

**Issue by myw** [pymzml/pymzML#29]
I see the newest changes have been merged in (thank you!) and the version has been bumped, but PyPI still has [0.7.5 as its newest one](https://pypi.python.org/pypi/pymzML)—someone should make sure it has 0.7.6.

Thanks!

**Comment by JB-MS** [comment]
Hello,

we will take care of it. Thanks for the information.

With best regards,
J. Leufken
