### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'TIC'

### ISSUE THREAD

**Issue by btoro** [pymzml/pymzML#30]
Just began using your software. I get the following error when I try out the example scripts:

Downloading file ...
Downloading file completed.

Traceback (most recent call last):
  File "C:\Python27\Scripts\pymzML\example_scripts\accessAllData.py", line 46, in <module>
    main(verbose = True)
  File "C:\Python27\Scripts\pymzML\example_scripts\accessAllData.py", line 31, in main
    run = pymzml.run.Reader(example_file, MSn_Precision = 250e-6)
ValueError: invalid literal for int() with base 10: 'TIC'

**Comment by JB-MS** [comment]
Hello,

this was a small bug in the current version. If you clone the module from: https://github.com/pymzml/pymzML.git the error should be fixed. The version on pypi is not the latest one.

With best regards,
J. Leufken
