### ISSUE TITLE
run.Writer issue

### ISSUE THREAD

**Issue by caetera** [pymzml/pymzML#35]
Implementation of _addTree method in mzML Writer has the following issue.

run.py line 723
 ```
        if typeOfSpec not in self.lookup.keys():
            self.lookup['{0}List'.format(typeOfSpec)] = \
                cElementTree.Element('{0}List'.format(typeOfSpec), {'count': 0})
            self.lookup['{0}Indeces'.format(typeOfSpec)] = \
                cElementTree.Element('index', {'name': typeOfSpec})
```

Since lookup has keys, that are similar to "(typeOfSpec)List", the corresponding element is reinitialized on each call, leading to only one spectrum in the result file
Possible fix:
```
        if '{0}List'.format(typeOfSpec) not in self.lookup.keys():
            self.lookup['{0}List'.format(typeOfSpec)] = \
                cElementTree.Element('{0}List'.format(typeOfSpec), {'count': 0})
            self.lookup['{0}Indeces'.format(typeOfSpec)] = \
                cElementTree.Element('index', {'name': typeOfSpec})
```

**Comment by caetera** [comment]
Additionally the spectrum should be dereferenced (Spectrum.deRef method), before it can be written. It might be good idea to have this included in the documentation and use examples, or, probably in the code of the method itself, since most of the users will probably want to write a copy of the spectrum anyway.

**Comment by fu** [comment]
good point. There were several requests / issues with our writer and I am sorry to say that it is still in alpha. We never intended to have the functionality to write mzMLs, but the reviewer insisted ;) Anyways, we should be able to bring out the writer from the alpha stage to something more serious during the next iteration (publication) of pymzML. In the meantime, if you could open up a pull request, than I could credit you with the fix - otherwise, i"ll add it myself :)

Thanks

**Comment by caetera** [comment]
Yes, sure, I can do this.
It is, actually, sad to hear that Writer was not intended to exist, since, I was mostly interested in the way to write mzML files from python and even was close to implementing some writer myself.
I really appreciate your work. To my knowledge pymzml is the only existing module that can write mzML from python. Thus I think it is very important to have it implemented and I will be happy to help with it, if necessary, however I am not sure how much time and resources I could spend on it.

**Comment by fu** [comment]
Thanks for the fix! I would definitely come back to you when we try to work on the next iteration of pymzML; it might even be version 1.0! :) 

My aim was to contact all contributors towards the end of this year and start a conversation about the next iteration. Ultimately, I'd like to submit a paper in the first half of 2017, the more authors/contributors the better :).

**Comment by caetera** [comment]
Great.
