### ISSUE TITLE
test.dat.igzip installs to /usr/lib/python3.12/dist-packages

### ISSUE THREAD

**Issue by lopippo** [pymzml/pymzML#367]
Greetings,

when the install_lib target is run, the 
```
.pybuild/cpython3_3.12_python-pymzml/build/test.dat.igzip
```

is installed to 
```
usr/lib/python3/dist-packages/test.dat.igzip
```

In the Debian distribution, no file belonging to a Python package can be installed in that directory.

I can't figure out how that test.dat.igzip file is created. Where should it be installed ?

Thank you,
Filippo

**Comment by MKoesters** [comment]
Hi Filippo,

The file is created during this test: https://github.com/pymzml/pymzML/blob/cb8a479992df7d0e9bd833621c53a24be49bba50/tests/file_io_indexed_gzip_writer_test.py

test.dat.igzip is the default filename for the output file of the indexed gzip writer here: https://github.com/pymzml/pymzML/blob/cb8a479992df7d0e9bd833621c53a24be49bba50/pymzml/utils/GSGW.py#L57

We could change the test to write to a temporary directory, it does not matter much, where the file is created

**Comment by lopippo** [comment]
Sorry, for some reason I do not get the notifications by email. 

So, yes, I would definitely recomment not saving that file in such a location that, upon install, the file will land in /usr/lib/python3/dist-packages/. I think that file should be output to the pymzml-specific directory (/usr/lib/python3/dist-packages/pymzml), no ?
