### ISSUE TITLE
Sanity check fails for chromatogram mzML

### ISSUE THREAD

**Issue by hroest** [pymzml/pymzML#38]
The sanity check introduced in 1db05a01ea8447f1355dc5e3adac55ed4d78552d fails for mzML files that do not contain spectra and only chromatograms. As the chromatogram ids do not conform to the regex, the sanity check fails the file parses incorrectly.

**Comment by MKoesters** [comment]
Hello,

we're currently working on another version, which will use different classes for spectra and chromatograms. This problem will also be fixed in the next version.

Manuel
