### ISSUE TITLE
Type error when loading files from StringIO

### ISSUE THREAD

**Issue by KeironO** [pymzml/pymzML#44]
Hey there,

I would like to use pymzML to load files from StringIO, but whenever I do this I get the following error.

``` python
  File "/home/keo7/.projects/omicsdb/src/run.py", line 333, in process_files
    ms_run = pymzml.run.Reader(d)
  File "/usr/local/lib/python2.7/dist-packages/pymzml/run.py", line 155, in __init__
    self.info['fileObject'], self.info['seekable'] = self.__open_file(path, file_object)
  File "/usr/local/lib/python2.7/dist-packages/pymzml/run.py", line 197, in __open_file
    self.info['encoding'] = self.__determine_file_encoding( path )
  File "/usr/local/lib/python2.7/dist-packages/pymzml/run.py", line 173, in __determine_file_encoding
    if os.path.exists( path ):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, instance found
```

The offending code is...

```
        d = StringIO(x[1])
        ms_run = pymzml.run.Reader(d)
```

Any help would be much appreciated(!)

**Comment by KeironO** [comment]
I've still had no joy with this, it seems as if pymzml is unable to take files, and only paths?

**Comment by fu** [comment]
Hi KeironO,

pymzml is actually able to use file objects when the run is initialized with kwarg _file_object_. Not sure if this feature propagated into the actual docu. However, we are currently working on pymzML V1.0, which comes with lots of new cool features, CI and auto-doc generation.

Hope _file_object_ works with you code, please let me know if otherwise.

Best regards,

Christian

**Comment by KeironO** [comment]
Still not been able to do this with StringIO with the file_object argument.

```
mzML_files.append([x.FILE_NAME, StringIO(x.RAW_FILE)])
            for y in mzML_files:
                ms_run = pymzml.run.Reader(file_object=y[1])
```

Throws up the following error.

```
TypeError: coercing to Unicode: need string or buffer, NoneType found

```

**Comment by KeironO** [comment]
I have still not been able to resolve this problem.

**Comment by fu** [comment]
Hi and sorry for the delay.
We are currently working on a new release and we have wrapped the file objects into new classes, thus we cannot fix this issue right now. Sorry.  However, we will test this issue with the new classes as soon everything is ready to be published.

**Comment by JB-MS** [comment]
@KeironO  The new pymzML v2.0.2 is out! Have you tried out this new version?
