### ISSUE TITLE
Possible error in the test_deconvolution.py

### ISSUE THREAD

**Issue by AdamSorrel** [pymzml/pymzML#47]
Hi there,

I am not sure whether this isn't just an issue of my computer, but when running the test_deconvolution.py I have run into a following error:
`python test_deconvolution.py 
Traceback (most recent call last):
  File "test_deconvolution.py", line 26, in <module>
    import get_example_file
ImportError: No module named 'get_example_file'
`

It turns out it's trying to call `sys.path.append('example_scripts')` which is not a subfolder. Changing it to `sys.path.append('../example_scripts')` resolved the issue. 

I thought you might want to know.

Adam

**Comment by AdamSorrel** [comment]
I still got a bunch of errors afterwards though all of which have the same issue `KeyError: 'count'`.

`
python test_deconvolution.py 
../example_scripts/get_example_file.py:58: ResourceWarning: unclosed file <_io.BufferedReader name='../example_scripts/mzML_example_files/deconvolution.mzML.gz'>
  checked_file = check_file(filename_with_path, filename)
EEE

ERROR: test_deconvolution_with_debug_parameter (__main__.TestDeconvolution)

Traceback (most recent call last):
  File "test_deconvolution.py", line 32, in setUp
    run = pymzml.run.Reader(example_file, MS1_Precision = 5e-6, MSn_Precision = 20e-6)
  File "/home/doron/.local/lib/python3.5/site-packages/pymzml/run.py", line 299, in __init__
    self.info['spectrum_count'] = element.attrib['count']
KeyError: 'count'

ERROR: test_devonvolution_intensities (__main__.TestDeconvolution)

Traceback (most recent call last):
  File "test_deconvolution.py", line 32, in setUp
    run = pymzml.run.Reader(example_file, MS1_Precision = 5e-6, MSn_Precision = 20e-6)
  File "/home/doron/.local/lib/python3.5/site-packages/pymzml/run.py", line 299, in __init__
    self.info['spectrum_count'] = element.attrib['count']
KeyError: 'count'

ERROR: test_masses (__main__.TestDeconvolution)

Traceback (most recent call last):
  File "test_deconvolution.py", line 32, in setUp
    run = pymzml.run.Reader(example_file, MS1_Precision = 5e-6, MSn_Precision = 20e-6)
  File "/home/doron/.local/lib/python3.5/site-packages/pymzml/run.py", line 299, in __init__
    self.info['spectrum_count'] = element.attrib['count']
KeyError: 'count'

----------------------------------------------------------------------
Ran 3 tests in 0.056s

FAILED (errors=3)
`

**Comment by AdamSorrel** [comment]
Hi Manuel,

Thank you for  your quick reply. I am sorry I didn't add details about my python package. I have tried to install pymzml on a different computer and the error was repeated. 

I'm using python3.5 Anaconda distribution with the pymzml version 0.7.6. I'm attaching the environment file. It should be possible to recreate an exact copy in your computer with this command `conda env create -f environment.yml` . 

[pymzml_env.yml.zip](https://github.com/pymzml/pymzML/files/344979/pymzml_env.yml.zip)

I wouldn't worry about it too much if you're already reworking the whole thing. Good luck!

**Comment by JB-MS** [comment]
New version will handle this properly.
