### ISSUE TITLE
Modifying and saving an mzML file

### ISSUE THREAD

**Issue by AdamSorrel** [pymzml/pymzML#48]
I was trying to load an mzML file, modify it and save the result. Since I'm trying to bin the m/z values, I was using my own function for it. It wasn't completely clear to me how is one supposed to proceed, but I assume it's something like this: 

```
runIN = pm.run.Reader("Blank1.mzML")
# Just to make sure nothing will collide in the process
runIN2 = runIN

# Binned values of m/z
newMZ = list(np.arange(20,450, 0.25))

runOUT = pm.run.Writer(filename='write_test.mzML', run=runIN2, overwrite=True)
for spec in runIN:
        # Producing binned intensity values
        specBin = mpm.binning(spec,20,450,0.25)
        # Saving the new m/z values
        spec.mz = newMZ
        # Saving the intensity values
        spec.i = list(specBin)
        # Saving the list of tuples in of peaks
        spec.peaks = list(zip(newMZ, list(specBin)))
        runOUT.addSpec(spec)

runOUT.save()
```

Checking the spectrum, the values did get assigned, but for some reason the output is not saved properly. A file is generated, but the spectra aren't saved properly. I'm not sure, but my impression was that it might confuse the 'chromatogram' and 'spectrum' tags at some point, but it's only a speculation. 

I know the `run.Writer` is a beta, but it's definitely a key function. At least for me. 
I was trying to understand what is going on in the `run.Writer` module, but I didn't manage to get into it, without more information. 

Thanks so much for your help. 

Adam

**Comment by MKoesters** [comment]
Hi Adam,

since we are currently developing a new version, we cant fix this issue at this point.
However, we'll keep this issue in my mind so we can fix this for the new version.
Also, which kind of information are you missing to get into the Writer class?

Manuel

**Comment by JB-MS** [comment]
Can this be closed? Any new developments?

**Comment by JB-MS** [comment]
Closed after a year idle time...
