### ISSUE TITLE
Plotly missing from setup.py

### ISSUE THREAD

**Issue by Chris7** [pymzml/pymzML#51]
Hi guys, just a heads up that your setup.py is missing plotly as a required dependency. This causes imports to break on clean installs.

**Comment by fu** [comment]
Hi Chris,

thanks for pointing it out. We will fix this asap or just send us a pull request :) - otherwise we are working on a totally revamped version of pymzml, so stay tuned !! :)

Cheers

.c

**Comment by Chris7** [comment]
Done in #52. Wanted to make sure you wanted a dependency before adding one.

**Comment by JB-MS** [comment]
Thanks for the pull request!
