### ISSUE TITLE
Missing psi-ms-4.0.1.obo in pip install

### ISSUE THREAD

**Issue by mortonjt** [pymzml/pymzML#59]
When I tried to `pip install pymzml`, the `psi-ms-4.0.1.obo` file was never downloaded with the pip install.  Ended up having to directly download this file from github.

Certainly not a deal breaker, but was an obstacle to getting started with this tool.

**Comment by JB-MS** [comment]
Hello Jamie,

thanks for your comment. We are working currently on a new version of pymzml. This obo version will then also be included again in the pip package, which has not been updated for some time.

To stay always up to date, clone directly from github.

Cheers,
Johannes

**Comment by JB-MS** [comment]
PyPI was updated to 0.7.8.

Cheers,
Johannes
