### ISSUE TITLE
spectrum.deconvolute_peaks issue

### ISSUE THREAD

**Issue by infusini** [pymzml/pymzML#60]
Hi,

I am working with centroided Bruker TOF data and I keep getting an error while using the _deconvolute_peaks_ for MS2 spectra:

`Found more than one peak. This is not expected`

I found only a closed issue with no response on the subject. Is there anything I can do to avoid this issue? Am I doing something wrong?

```
msrun = pymzml.run.Reader("fileName.mzML")

for spectrum in msrun:
   if (spectrum["MS:1000511"] == 2):
      msmsSpectrum = spectrum.deconvolute_peaks(ppmFactor=4, minCharge=1, maxCharge=5)
```

Thank you,

Peppe

**Comment by JB-MS** [comment]
Hi Peppe,

thanks for using pymzml :)

I would need to take a closer look at the data, to help you in this case. Maybe you could provide a test file, where the function does not work.

We are working also on a new release of pymzml. Maybe the deconvolution functions will be restructured, since they were not maintained/updated for some time.

Cheers,
Johannes

**Comment by fu** [comment]
Hi Peppe,

I agree with Jeo, we are getting rid of deconvolute peaks since we do not have an updated code base for this in the newer pymzML version (soon to be released! :))). There might be an alternative version/code on the horizon, but I have to look into this.

Sorry about that.

Cheers
.c


Cheers

.c

**Comment by JB-MS** [comment]
@infusini Sorry, we lost track of this issue in the re-publication process... Do you still need help on this?

**Comment by infusini** [comment]
Hi @JB-MS,

apologies, I missed your message. Yes, in fact, I would still need it. I have found a workaround, but it's not efficient at all. I am about to try [this](https://github.com/mobiusklein/ms_deisotope) (in case you haven't come across it).

But it would be great to have it all in one...

Cheers,
Peppe

Peppe

**Comment by fu** [comment]
Hi Pepe,

yes we know of @mobiusklein code - definitely a path forward as we have the original deconv. developer not on board anymore and currently no resources for that.  Maybe we can convince Joshua to move his code into the spectrum class :)

Cheers

.c

**Comment by mobiusklein** [comment]
Hello,

I'd be happy to write a wrapper method for `pymzml`. Such a wrapper would look like this:
```python
def deconvolute(self, *args, **kwargs):
    from ms_deisotope.deconvolution import simple_peak, deconvolute_peaks
    peaks = self.peaks("centroided")
    # pack peak matrix into expected structure
    peaks = [simple_peak(p[0], p[1], 0.01) for p in peaks]
    decon_result = deconvolute_peaks(peaks, *args, **kwargs)
    dpeaks = decon_result.peak_set
    # pack deconvoluted peak list into matrix structure
    dpeaks_mat = np.zeroes((len(dpeaks), 3), dtype=float)
    for i, dp in enumerate(dpeaks):
        dpeaks_mat[i, :] = dp.neutral_mass, dp.intensity, dp.charge
    return dpeaks_mat
```
I should warn you that `ms_deisotope` is built on multiple C libraries for speed, and it has a gruesome data access layer of its own.

**Comment by fu** [comment]
Sounds great! As I understand Manuel is on the case!

**Comment by MKoesters** [comment]
Sry, this got lost somehow ...
I added the deconvolution functionality, however I could't make ms_deisotope an optional dependency, maybe because there is only a github release.
@mobiusklein do you plan to upload ms_deisotope to pypi?

**Comment by mobiusklein** [comment]
Yes. It's been continuously pushed back by other tasks, but I'll try to get to it by tomorrow evening. I think all of its dependencies are already there, so it's just a matter of making sure everything is sync'd up.

**Comment by MKoesters** [comment]
Super, thank you very much, however no hurry, this request will be pending until at least next Friday anyways ...

**Comment by mobiusklein** [comment]
I've uploaded all of `ms_deisotope`'s dependencies to PyPI with wheels for Windows Python 3.5-3.7. It was more labor than expected. As I've got the time, my new target is this Sunday.

**Comment by mobiusklein** [comment]
I've pushed  sdists and wheels to PyPI. Please let me know if any issues come up.

**Comment by MKoesters** [comment]
Everything works fine so far, thank your for your quick help :)
If something comes up, I'll make sure to let you know
