### ISSUE TITLE
'gbk' codec can't decode byte 0x93 in position 1081: illegal multibyte sequence

### ISSUE THREAD

**Issue by ATPs** [pymzml/pymzML#64]
import pymzml
f_mix = r"D:\Insects\ManducaSexta\2017Mansi\20170302MansiPGRP_EcPG\1485PGN2.mzML"
run_mix = pymzml.run.Reader(path=f_mix)

Traceback (most recent call last):

  File "<ipython-input-16-994202ec2154>", line 3, in <module>
    run_mix = pymzml.run.Reader(path=f_mix)

  File "C:\p\Anaconda3\lib\site-packages\pymzml\run.py", line 167, in __init__
    self.OT = self.__init_obo_translator(extraAccessions)

  File "C:\p\Anaconda3\lib\site-packages\pymzml\run.py", line 491, in __init_obo_translator
    'name': obo_translator[minimumMS],

  File "C:\p\Anaconda3\lib\site-packages\pymzml\obo.py", line 88, in __getitem__
    self.parseOBO()

  File "C:\p\Anaconda3\lib\site-packages\pymzml\obo.py", line 155, in parseOBO
    for line in obo:

UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1081: illegal multibyte sequence

The pymzML was downloaded from GitHub directly. Default obo version is psi-ms-3.79.0.obo, as shown in the psi-ms.obo file. I can get it work by setting obo_version="3.71.0" or earlier version.
I didn't find the 0x93 in other files. 
I am running windows 10 x64, Anaconda, python 3.6.0.

**Comment by JB-MS** [comment]
Hi,

thanks for using pymzML.

The problem you describe seems to be a more general problem (of Python3.6?, see [here](https://bugs.python.org/issue28758)).

However, i have adjusted the code, where the obo file is read to a defined utf-8 decoding. I hope that will solve the problem, but i have not reproduced the error so far in your mentioned environment.

Cheers,
Johannes

**Comment by ATPs** [comment]
Thanks, Johannes.
Yes, it's hard to say. Thank you for the reply. I can use the old version of obo file to make it work.

**Comment by ATPs** [comment]
I haven't found the reason also. I have several mzML files. The newest obo files work for one file, but not for others. Anyway, not a big problem now. Best!
Xiaolong
