### ISSUE TITLE
Release 0.7.8 to PyPI

### ISSUE THREAD

**Issue by myw** [pymzml/pymzML#65]
Hello!

For users of pymzML who manage larger codebases, it's very helpful to have up-to-date versions of pymzML on PyPI, so that we don't constantly have to be pointing to a git repo somewhere and can specify versions directly.

Could you please release your latest changes to PyPI?

You can even set this up for free with TravisCI so that any [tagged commits automatically deploy to PyPI](https://docs.travis-ci.com/user/deployment/pypi/) For an example of such a system, see the [ginkgobioworks/curious travis.yml file](https://github.com/ginkgobioworks/curious/blob/master/.travis.yml)

Any tagged commits (uploaded to github via, e.g., `git push --tags origin master`) automatically trigger an updated PyPI release.

I'd submit a PR for this myself, but it couldn't include the PyPI deployment part.

Thanks!

**Comment by JB-MS** [comment]
pymzML has been updated on PyPI to 0.7.8!

Thanks for the advice using Travis for such purpose, we will implement this for the new upcoming version. Stay tuned!

Cheers,
Johannes
