### ISSUE TITLE
Export more metadata

### ISSUE THREAD

**Issue by erwinvaneijk** [pymzml/pymzML#70]
Some values available in the mzml xml are not available/exported through the pymzml interface.

**Comment by JB-MS** [comment]
Hi,

which values exactly? Have you tried our new version 2.0.0?

Cheers,
Joe

**Comment by erwinvaneijk** [comment]
Hi Joe,

Thanx for your response!

We're looking at variables like the software version used to get the data off the MS (e.g. MS:1000678, which is inside the <softwareList> tags), and the startTimeStamp of a run. They're not exposed through the API, but necessary if you want to make people select the right experiment out of a collection of mzml files.

Erwin

**Comment by JB-MS** [comment]
Solved by #75. Thanks for the update!
