### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by jegreenwald** [pymzml/pymzML#71]
Installed version 2.0.0 using pip. 

Downloaded "plotAspec.py" directly from your current "master" branch. 

When I run it, I see: 

D-69-91-144-79:Downloads jegreenwald$ python plotAspec.py 
Traceback (most recent call last):
  File "plotAspec.py", line 25, in <module>
    import get_example_file
ModuleNotFoundError: No module named 'get_example_file'

**Comment by JB-MS** [comment]
Hi there,

we are currently migrating to version 2.0.0. Therefore some backward compatibility issues may arise. If you use example scripts, please use the v2.0.0 branch on Github or the shipped example script with pip version 2.0.0

Thanks for your patience and understanding.

Cheers,
Joe

**Comment by jegreenwald** [comment]
Hi Joe,

Thanks very much for your response. I am now using the example scripts in the v2.0.0 branch, but I am still getting the following error message when I try and run the plot_spectrum.py script. Do you have any other suggestions? 

OSError: Could not find obo file /anaconda3/lib/python3.6/site-packages/pymzml/obo/psi-ms-23:06:2017.0.0.obo

Best,
Julia

**Comment by aretaon** [comment]
Same here using pymzml 2.0.0 via anaconda and pip:

 File "[…]python3.5/site-packages/pymzml/spec.py", line 676, in __getitem__
    accession = self.calling_instance.OT[accession]['id']

 File "[…]python3.5/site-packages/pymzml/obo.py", line 109, in __getitem__
    self.parseOBO()

 File "[…]python3.5/site-packages/pymzml/obo.py", line 175, in parseOBO
    raise IOError("Could not find obo file {0}".format(obo_file))

OSError: Could not find obo file […]python3.5/site-packages/pymzml/obo/psi-ms-23:06:2017.0.0.obo

**Comment by jegreenwald** [comment]
Hi,

Thanks for pointing me to #61 . Fixing that error also worked for. However it was not necessary to change the whole line, just changing the version="23:06:2017" to version="4.0.1" fixes the issue. 

Ex if you change the file from the command line as follows, then the run command will run.Reader command will work for your .mzML file : 

sed -i -e 's/'23:06:2017'/'4.0.1'/g' FILENAME.mzML

Thanks for the help. If future versions of pymzml include the updated obo files such that this change becomes unnecessary, let me know. 

Best,
Julia

**Comment by JB-MS** [comment]
Hi Julia,

i tried to reproduce your problem using a virtualenv and I think the problem is that you need to run the example scripts inside the example_scripts folder, where the get_example_file.py script is located. The get_example_script.py is no Python module but rather a helper script for running some of the provided the example scripts.  Alternatively, link or copy this script to the location where you want to run your script. 

I hope this helps.

Cheers,
Johannes

**Comment by jegreenwald** [comment]
Hi Johannes,

Thanks very much for your advice and suggestion. I did not change the location of the get_example_file.py script, but I copied the parts of your example scripts that I wanted to use into a new script in a different directory (where my mzML files are located), and I am now able to use the functions that I want. 

I am new to Python and may have more questions in the future, but for now, I am able to use pymzML to  analyze my mass spec data. 

If a new obo file is added such that  the version ID doesn't need to be changed from 23:06:2017 to 4.01 for all mzML files containing Orbitrap LTQ data converted via the new MSconvert program, please let me know. 

Thanks for all your help,
Julia

**Comment by jegreenwald** [comment]
Hi Johannes,

Sorry for accidentally deleting my previous comment. Thanks for your message regarding how to fix the error when running example scripts.

I did not try running the example scripts inside the example scripts folder, but I was able to copy the parts of the example scripts that I wanted to use and then extract info from my mzml files. 

Thanks,
Julia
