### ISSUE TITLE
Could not find obo file: psi-ms-4.0.14.obo

### ISSUE THREAD

**Issue by jonison-zhang** [pymzml/pymzML#79]
Good afternoon, got an issue when executing py code, use MSconvert to get a *.mzML file, and when call the pymzml lib, it shows: OSError: Could not find obo file, C:\Anaconda3\lib\pymzml\obo\psi-ms-4.0.14.obo. Would you please help me on that? Thank you very much!

**Comment by JB-MS** [comment]
Hi!
Which version do you use? We are still in the migration process to 2.0.0, therefore we have not updated to obos for a while. You could add them manually in the pymzml/obo directory, if you need a quick solution.

Cheers,
Johannes

**Comment by JB-MS** [comment]
@jonison-zhang Version 2.0.0 supports 4.0.14

Cheers,
Johannes

**Comment by jonison-zhang** [comment]
Thank you very much for your kind reply. I am using 0.7.8 version, would
you please share some information about how to input the OBOs manually?

Thanks again.

Regards,

Jun

2017-12-04 8:39 GMT+00:00 Johannes Leufken <notifications@github.com>:

**Comment by JB-MS** [comment]
Hi,

download the required version of the obo file, e.g. from: https://github.com/pymzml/pymzML/blob/v2.0.0/pymzml/obo/psi-ms-4.0.14.obo.gz

Then, gunzip into your stated directory: C:\Anaconda3\lib\pymzml\obo\

Should work immediately.

Cheers,
Johannes

**Comment by jonison-zhang** [comment]
Thank you very much!!
Regards,
Jun

2017-12-04 9:55 GMT+00:00 Johannes Leufken <notifications@github.com>:
