### ISSUE TITLE
Filtering by spectrum function

### ISSUE THREAD

**Issue by remoore** [pymzml/pymzML#81]
I would like to be able to filter my mzML data by the function number that appears in the spectra headers:

`<spectrum index="217" id="function=1 process=0 scan=18" defaultArrayLength="129">`

Is it possible to extract this information directly? I have been trying to do this in a roundabout way using the extraAccessions keyword argument to the run.Reader class. I have been passing the tuple ('MS:1000796',['value']) in an attempt to extract the spectrum titles. Running this neither throws an error nor adds the spectrum titles to the spectra.

A pointer in the right direction would be much appreciated.

**Comment by MKoesters** [comment]
Hey remoore,

Did you make sure that your mzML file contains a cvParam such as <cvParam cvRef="MS" accession="MS:1000796" .../>? with an attribute 'value'?
If this is not the case, pymzML wont extract this value

If you are using v2.0.0, you could try to get the content of id by:
>>> run = pymzml.run.Reader('example.mzML')
>>> spec = run[1]
>>>id_string = spec.element.attrib['id']

in v.0.7.x you'd go for
>>> run = pymzml.run.Reader('example.mzML')
>>> spec = run[1]
>>> xml = spec.xmlTree
>>> top_level_element = next(xml)
>>> id_string = top_level_element.attrib['id']

Hope that works for you

Best,
Manuel

**Comment by remoore** [comment]
Manuel

Thanks for the quick response.

Yes, I checked that the mzML file contained the cvParam, but for some reason, it still didn't work.

I've tried the other approach you suggested with success, so this is no longer a problem for me.

Thanks for the help.

Cheers

Rob

**Comment by JB-MS** [comment]
Closing this issue since it is solved.

Thanks for using pymzML!
