### ISSUE TITLE
pymzml 2.0 removed option to re-build index from scratch

### ISSUE THREAD

**Issue by hroest** [pymzml/pymzML#88]
In the old pymzml it was possible to read files that were not `indexedmzML` files. We still encounter these quite often in the wild. This was possible through the option `from_scratch` passed to the `_build_index` function (this is in version 0.7.9):

https://github.com/pymzml/pymzML/blob/bcecfd2d31f0beed617afa29de82dc76caa66ad0/pymzml/run.py#L296-L300

However, now the option does nothing any more and the variable `from_scratch` is always set to False:

https://github.com/pymzml/pymzML/blob/903c207035dbd5ccf1ed9015fe5a6b0b32b8fd9a/pymzml/file_classes/standardMzml.py#L38

**Comment by hroest** [comment]
To solve this, I suggest to re-introduce the option and add the following function again to pymzml 2.0:

https://github.com/pymzml/pymzML/blob/bcecfd2d31f0beed617afa29de82dc76caa66ad0/pymzml/run.py#L346-L425

**Comment by hroest** [comment]
> This was removed since pymzml now uses binary jumps to find the spectrum, which works quite fast (given the file is not truncated).

Sorry, I dont quite understand. How do the binary jumps work if you dont have an index? What this code does is to build an index:

```
spec_name_xxx : 300
spec_name_yyy : 500
chromatogram_PEPTIDE_AAA : 800
chromatogram_PEPTIDE_BBB : 900 
```

so if I request `chromatogram_PEPTIDE_AAA` how will you be able to find it quickly if you have no idea where in the file it is?

**Comment by hroest** [comment]
PS: a good example file would be this one https://drive.google.com/open?id=1CPasmk0gpVqd6i4Y72_ocri4aL7CvlE2 with the index removed

**Comment by MKoesters** [comment]
I reimplemented build_index_from_scratch, just set build_index_from_scratch to True when initializing the run object. #
Also #87 should be fixed now

The binary jumps starts in the middle of the file, parses the index from the spectrum title and adds it to the offset dict.
If its not the index spectrum your are looking for, it does an (interpolated) binary jump to the lower or upper half, depending if your ID is bigger or smaller than the one you are looking for.
But of course you are right, if the index is a string, you have no chance to make a good guess, where your spectrum/chromatogram is.

**Comment by hroest** [comment]
> But of course you are right, if the index is a string, you have no chance to make a good guess, where your spectrum/chromatogram is.

which it is in our case where we have chromatograms, so the re-building of the index is essential
