### ISSUE TITLE
TypeError: 'method' object is not iterable for Plotting Chromatogram example

### ISSUE THREAD

**Issue by realperson999** [pymzml/pymzML#95]
I'm trying to follow the plotting a chromatogram example script from the latest docs.

The script is failing when adding attributes to Factory().new_plot()

```
    pf.add(
        run['TIC'].peaks,
        color = (0, 0, 0),
        style = 'lines',
        title = mzml_basename
    )
```

returns: TypeError: 'method' object is not iterable
for each member in that list as I comment them out one by one

I had just previously realized an issue where calling run['TIC'] on a file that was converted using zlib compression would throw the same error and point to the same code in:

   line 379, in add in plot.py
    x_vals = [mz for mz, i in data if mz_range[0] <= mz <= mz_range[1] and int_range[0] <= i <= int_range[1]]

I'm not sure if they're related but the bottleneck is the same and I can't seem to find out why this doesn't go through.

**Comment by MKoesters** [comment]
Hey, thanks for using pymzml

Are you using version 2.0?
If yes, try to use run['TIC'].peaks()

We changed the interface, there should also be a warning indicating that.
If this is not the issue, let me know and I'll have a close look.

Best,
Manuel

**Comment by realperson999** [comment]
Yes that worked.

I didn't see any warnings pop up about it, the docs page is also written without it.
https://pymzml.readthedocs.io/en/latest/example_scripts.html#parsing-a-mzml-file-new-syntax

Thanks for your help :) Let me know if you have any other questions.

**Comment by MKoesters** [comment]
Thank you too for reporting this, I'll make sure to edit the docs before closing this issue

Best,
Manuel

**Comment by abhipathak1004** [comment]
i am still facing this issue.
![image](https://user-images.githubusercontent.com/24479242/51231307-0533b700-1989-11e9-8844-72947c33769a.png)

**Comment by JB-MS** [comment]
@abhipathak1004 Which version of pymzML do you use?

When using version >2.0 you have to retrieve the peaks like this:

`msrun['TIC'].peaks()`

And for spectra e.g.:

`spectrum.peaks('raw')` 
`spectrum.peaks('centroided')`


peaks is no longer a property but a function. Hope this helps!

Cheers,
Johannes

**Comment by JB-MS** [comment]
I have edited the corresponding example script, this should now also be correct in the docu.
